import bcrypt from 'bcryptjs'

const data = {
  users: [
    {
      name: 'Samael',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Tati',
      email: 'tati@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Violão Clássico Yamaha',
      slug: 'violao-classico-yamaha',
      category: 'Violões',
      image: '/images/violao1.jpg',
      price: 450,
      brand: 'Yamaha',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Violão clássico de alta qualidade com som cristalino',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      name: 'Guitarra Elétrica Fender',
      slug: 'guitarra-eletrica-fender',
      category: 'Guitarras',
      image: '/images/guitarra1.jpg',
      price: 1200,
      brand: 'Fender',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'Guitarra elétrica profissional com som potente',
      isFeatured: true,
      banner: '/images/banner2.jpg',
    },
    {
      name: 'Teclado Casio 61 Teclas',
      slug: 'teclado-casio-61',
      category: 'Teclados',
      image: '/images/teclado1.png',
      price: 350,
      brand: 'Casio',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'Teclado compacto com 61 teclas e múltiplos sons',
    },
    {
      name: 'Bateria Acústica Pearl',
      slug: 'bateria-acustica-pearl',
      category: 'Baterias',
      image: '/images/bateria1.jpg',
      price: 2500,
      brand: 'Pearl',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Bateria acústica profissional com som excelente',
    },
    {
      name: 'Saxofone Alto Yamaha',
      slug: 'saxofone-alto-yamaha',
      category: 'Sopros',
      image: '/images/saxofone1.jpg',
      price: 1800,
      brand: 'Yamaha',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'Saxofone alto com som quente e responsivo',
    },
    {
      name: 'Baixo Elétrico Ibanez',
      slug: 'baixo-eletrico-ibanez',
      category: 'Baixos',
      image: '/images/baixo1.jpg',
      price: 900,
      brand: 'Ibanez',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'Baixo elétrico com som profundo e dinâmico',
    },
  ],
}
export default data
